### ISSUE TITLE
Thanks for this project. It is very helpfull for me.

### ISSUE THREAD

**Issue by jhs512** [gdraheim/docker-systemctl-replacement#1]
Thanks for this project. It is very helpfull for me.

The issues is

command> systemctl.py start mysql
Failed to get D-Bus connection: Operation not permitted
ERROR:systemctl:returncode 1
 /bin/sh -c "systemctl unset-environment _WSREP_START_POSITION"
Traceback (most recent call last):
  File "/usr/bin/dctl", line 1612, in <module>
    result = command_func(*modules)
  File "/usr/bin/dctl", line 854, in restart_of_units
    elif not self.restart_unit(unit):
  File "/usr/bin/dctl", line 862, in restart_unit
    return self.restart_unit_from(conf)
  File "/usr/bin/dctl", line 883, in restart_unit_from
    self.start_unit_from(conf)
  File "/usr/bin/dctl", line 627, in start_unit_from
    subprocess_wait(cmd, env, check=check)
  File "/usr/bin/dctl", line 264, in subprocess_wait
    raise Exception("command failed")
Exception: command failed

docker env
- centos 7.0
- mariadb

**Comment by gdraheim** [comment]
I have created testcase 8001. It seems that "yum install mariadb" does not install a server, you do probably need "yum install mariadb-server".

However the testcase uses a docker image for centos 7.0 (and centos 7.1) which can not install the mariadb-server packages. I do not know if that is a problem in my area - please have a test.

./testsuite.py test_8001 -vv

**Comment by gdraheim** [comment]
After double-checking with mariadb-server I have found a bug in the mariadb systemd setup => their mysqld_safe controller does IGNORE all signals from the systemd service (emulated by systemctl.py), so that there is NEVER a clean shutdown of the mysqld database.

If you do want to regularly start/stop mysqld (in a container or not) then you may want to send a bug report upstream to the mariadb guys that their systemd setup is BROKEN.

I have modified test_8001 so that it succeeds for now (after TimeoutSec=300 of mariadb.service).

**Comment by gdraheim** [comment]
I'll close it at latest of the 0.9 release.
