### ISSUE TITLE
Running systemctl.py as a init process in a runtime container

### ISSUE THREAD

**Issue by krisklau** [gdraheim/docker-systemctl-replacement#100]
Hi,

I am trying to utilize systemctl.py as an init manager in a container running on an embedded device. The container is based on ubuntu, and has a lot of pre-enabled services. 

What is the prefered strategy to start only the services I am creating? As far as I can see, there are several options: 

1. Manually delete all the *.wants files to disable the services, and then enable my services. 
2. Create a new target, and use that instead of the multi-user.target

I tried 2.), but had some issues setting the default with systemctl.py. I am able to set the default target, but the change seems not reflected in the code as far as I can tell. By changing the hardcoded default target value in systemctl.py I was able to set my target as default, but still a lot of other services popping up when I print `systemctl default-services`. (I notices the discussion in #32)

I am running the latest stable release. I see a lot of development in the dev-branch which I might need (such as #78), so might try that as well. 

What is the preferred approach?

Best,
Kristian

**Comment by krisklau** [comment]
Upon some digging, I found that the rouge services was listed in `/etc/rc3.d/`. Is there a way to disable these? I guess multi-user.target is rougly run-level 3, and could potentially only start those services if the target is indeed multi-user.target?

**Comment by gdraheim** [comment]
I have a couple of tests scenarios on the public base images by the vendors, you can have a look at https://github.com/gdraheim/docker-systemctl-images for some of them. So far I checked to extend the "igno_" services list in the python code, so that only services are being run that were enabled in the dockerfile.

So there could also be the approach to extend the igno_xx list if you have a number of services that will clearly not be relevant to any application container in the future.

At the moment, systemctl.py does not support to start different targets. The code is prepared for that, so I you were able to do that patch, but it was never really tested. So for the moment option 1 is they way to go (instead of delete actions, some "systemctl mask" may work as well).

The dev branch will be rolled out soon, so that v1.5 becomes the master. I am currently checking to improve the code coverage which has fallen below 90% (use "make checks" to have a look) - depending of how much time I have it is a couple of weeks away. Actually, I would need to have some time more than that to support users after the change, because there are some breaking changes which might interfere with projects who do currently wget master/systemctl.py - so it can not be earlier than June/July as I have a lot of stress in my day job atm.

**Comment by krisklau** [comment]
Thanks!

I took a look at the example images, and indeed they were much more clean than mine. I suspect then my setup is a bit unusual as I am basing it on a ubuntu-image I do not have direct control over, which has a lot of extra packages installed. 

I ended up following your advice to remove the servies. Used the following script, which might be useful for others: (NB: Untested on other systems, requires awk and xargs)

`systemctl list-unit-files --state=enabled --no-pager --no-legend --full | awk '{print $1}' | xargs systemctl disable`

In addition I had to re-run it after installing systemctl.py, as it observed some files in rc3.d that was ommited by the above systemctl print (apport and console.setup.sh)

`systemctl default-services --no-pager --no-legend --full | awk '{print $1}' | xargs systemctl disable`

I ran some of the checks, and I will try to help increase the coverage for develop. 

As for the comment on wget-master; I found this project via https://unix.stackexchange.com/questions/187042/starting-services-without-systemd which suggest precisely that, just FYI.
