### ISSUE TITLE
Support multiple ExecStop commands

### ISSUE THREAD

**Issue by Crack** [gdraheim/docker-systemctl-replacement#49]
It's valid to have multiple ExecStop commands. Currently units that use them fail to start with:
```
ERROR:systemctl: redis-server.service: there may be only one ExecStop statement (unless for 'oneshot' services).
                        Use ' ; ' for multiple commands or better use ExecStopPost
```

It's used eg. by Redis packages: official Debian, Ubuntu PPA (ppa:chris-lea/redis-server):
```
ExecStartPre=-/bin/run-parts --verbose /etc/redis/redis-server.pre-up.d
ExecStartPost=-/bin/run-parts --verbose /etc/redis/redis-server.post-up.d
ExecStop=-/bin/run-parts --verbose /etc/redis/redis-server.pre-down.d
ExecStop=/bin/kill -s TERM $MAINPID
ExecStopPost=-/bin/run-parts --verbose /etc/redis/redis-server.post-down.d
```

**Comment by gdraheim** [comment]
Thanks for the info. Actually, the implementation of systemctl.py does support more commands per option but for compatibility with systemd there is an additional syntax check with strong warnings. I had been under the impression that the systemd documentation had an entry about just a single command for ExecStop as well.

However, looking into https://www.freedesktop.org/software/systemd/man/systemd.service.html does not really restrict it explicitly. So I may just as well reduce the information to a warning - so that the returncode will be 0.

**Comment by gdraheim** [comment]
Already in release v1.4.2456
