### ISSUE TITLE
Feature: Support restarting failed services

### ISSUE THREAD

**Issue by haydenm315** [gdraheim/docker-systemctl-replacement#78]
If using daemon mode, it would be a worthy feature to support restarting units that fail.

**Comment by gdraheim** [comment]
This has not been very high on my TODO list. I know that it can be useful but then we have Healthcheck options in Docker and Kubernetes which offer a far better service than just looking for a dead pid.

I would take patches but I guess I wouldn't develop it within the next year.

**Comment by haydenm315** [comment]
We're eventually moving to kubernetes and will run containers using a
single process per container approach, but in the interim we're running
multiple processes in the container.  I've found your script useful, but we
need a way to ensure the services will restart if they exit for some
unknown reason. In order to provide some resilience, this is what I came up
with.

Hayden

**Comment by gdraheim** [comment]
I have merged the patch but I think that it is actually only a part of the functionality as systemd service descriptors support some settings on the restart policy.

https://www.freedesktop.org/software/systemd/man/systemd.service.html

RestartSec=
Configures the time to sleep before restarting a service (as configured with Restart=). Takes a unit-less value in seconds, or a time span value such as "5min 20s". Defaults to 100ms.

Restart=
Takes one of no, on-success, on-failure, on-abnormal, on-watchdog, on-abort, or always. If set to no (the default), the service will not be restarted. If set to on-success, it will be restarted only when the service process exits cleanly. In this context, a clean exit means an exit code of 0, or one of the signals SIGHUP, SIGINT, SIGTERM or SIGPIPE, and additionally, exit statuses and signals specified in SuccessExitStatus=. If set to on-failure, the service will be restarted when the process exits with a non-zero exit code, is terminated by a signal (including on core dump, but excluding the aforementioned four signals), when an operation (such as service reload) times out, and when the configured watchdog timeout is triggered. If set to on-abnormal, the service will be restarted when the process is terminated by a signal (including on core dump, excluding the aforementioned four signals), when an operation times out, or when the watchdog timeout is triggered. If set to on-abort, the service will be restarted only if the service process exits due to an uncaught signal not specified as a clean exit status. If set to on-watchdog, the service will be restarted only if the watchdog timeout for the service expires. If set to always, the service will be restarted regardless of whether it exited cleanly or not, got terminated abnormally by a signal, or hit a timeout.

As exceptions to the setting above, the service will not be restarted if the exit code or signal is specified in RestartPreventExitStatus= (see below) or the service is stopped with systemctl stop or an equivalent operation. Also, the services will always be restarted if the exit code or signal is specified in RestartForceExitStatus= (see below).

Note that service restart is subject to unit start rate limiting configured with StartLimitIntervalSec= and StartLimitBurst=, see systemd.unit(5) for details. A restarted service enters the failed state only after the start limits are reached.

Setting this to on-failure is the recommended choice for long-running services, in order to increase reliability by attempting automatic recovery from errors. For services that shall be able to terminate on their own choice (and avoid immediate restarting), on-abnormal is an alternative choice.

**Comment by gdraheim** [comment]
btw, I have added a check so that the default "Restart=no" make the unit to be not restarted. 

I did need that as otherwise a testcase from the testsuite.py would fail.

**Comment by gdraheim** [comment]
I have implemented RestartSec as well - I figured that it is needed to develop a testcase for the testsuite.py

Since there is no testcase I can not even say if the new features do work at all.

**Comment by gdraheim** [comment]
I have also implemented that restarts do not occur while the system is starting or stopping, so that we can get a clean shutdown of a container.

Plus I have written the testcase - which is a requirement for any release. It is only a minimal one showing that non-Restart services are ignored that do-Restart services are actually restarted.

make test_5700
