### ISSUE TITLE
Bootttime incorrect

### ISSUE THREAD

**Issue by haydenm315** [gdraheim/docker-systemctl-replacement#80]
The get_boottime function relies on the modified timestamp of the /proc/[pid]/stat file.  I've observed this file's timestamp change in an hour.  When this happens, the boottime may end up with a value after started unit's timestamp.  This can cause the service status files to get truncated which causes systemctl start/stop commands not to work.

**Comment by gdraheim** [comment]
Errr, I didn't see that so far. How does it happen?

Specifically, get_boottime watches for PID 1 which does usually exist.

**Comment by gdraheim** [comment]
Ahhh, I just saw that you provide patches. And the get_boottime one does look very sophisticated if I may say so. :) 

... I'll have a look at it tomorrow (it's about midnight CET).

**Comment by haydenm315** [comment]
I'm running systemctl as the entry point, so it's PID 1.  I've observed the
last modified time change on the /proc/1/stat file.  It seemed to happen
after about an hour.  Maybe the stat file changes over time?  When this
happens, all of the running services report as failed and
stop/start/restart commands don't have any effect.  The /var/run/*.status
files are all 0 length because systemctl has truncated them.  Could you
explain the logic behind this?  I'm running systemctl with my restart
failed service modifications, but a call to get the status for a service
should call the same function which gets the boottime.  You could also
observe the modified timestamp on the stat file and see if it changes over
time. My host OS is CentOS7.  That may play a part.

Hayden

**Comment by gdraheim** [comment]
By the way, I have learned that /proc/stat contains a "btime" field which is supposed to represent boot time. It is mentioned as being constant / same for all pids.

http://man7.org/linux/man-pages/man5/proc.5.html =>

btime 769041601
                     boot time, in seconds since the Epoch, 1970-01-01
                     00:00:00 +0000 (UTC).

So, I think your patch may be overly complex and it is "btime" that may be given a chance to fix the situation.

**Comment by haydenm315** [comment]
I agree this is simpler and accomplishes the same with less.

Hayden

**Comment by gdraheim** [comment]
However, I don't know if "btime" represents the boot time of the container (which we want) or the host system (which we do not want). I hadnt' time to analyse that so far. However you seem to target the "uptime" index which must be a derivative of the boot time as we would want it.

**Comment by haydenm315** [comment]
The btime seems to represent the boot time of the host system. See below.

hmyers@hmyers-dev:~$ ssh -lansible 172.28.12.248
Last login: Mon Oct  7 10:35:46 2019 from 172.28.148.55
[ansible@artemis ~]$ uptime
 10:41:37 up 12 days, 44 min,  2 users,  load average: 17.80, 13.70, 8.52
[ansible@artemis ~]$ cat /proc/stat | grep btime
btime 1569419800
[ansible@artemis ~]$ docker ps
CONTAINER ID        IMAGE
                                                 COMMAND
 CREATED             STATUS              PORTS               NAMES
96a5176cbcbf
registry.skyts.io/appliance/sfs-repos/skyline-sfs/5-0-0-rc-14:c1bb61688ca0fa935649a165138418111cd246b5
  "systemctl -1 default"   2 days ago          Up 2 days
            SFS1000
[ansible@artemis ~]$ docker exec -it SFS1000 cat /proc/stat | grep btime
btime 1569419800

**Comment by gdraheim** [comment]
Trying to understand your patch, I am not sure it is correct.

It seems that is computing clock ticks for the boot time which effectilvy turns the computations to be based on a linear time. However we really want a file time - just one where we know that older status files are not part of the current container execution. That is really some ntp based clock time  - of course clock time skew is probably just a second or two. May be it is just me who sees that it is not a time result related to a file time?

**Comment by gdraheim** [comment]
Forget about my last comment - I just saw that the last computation is subtracting from "time.time()" which ntp based.

However, the code brings me to another idea in that one can compute the boot time of the container simply by subtracting the "/proc/uptime" value from the clock time. There is not need to scan through the list of /proc/x files at all.

That'd be nice.

**Comment by gdraheim** [comment]
So there is a time.time() in the computation to get the current wall clock.

Since both /proc/uptime and /proc/x/stat represent run times related to the host system, one could also just add the proc run time to the btime and that would yield another ntp based time. It is just unsure what s better here.

**Comment by gdraheim** [comment]
Here's a patch that shows the different

How to test - create a container and run "systemctl.py daemon-reload -vvvv" in it

It seems that the result of "now() - uptime()" is always changing on the subsecond value. Using "btime()" as the basis to add the started-secs results in a constant value.

Since the btime() based value is a bit lower on my system I think that it is better - it's in the range of 300ms which I think is good enough that no commited files from the container's base image get treated as current x.status files. But you may object to that.

**Comment by gdraheim** [comment]
I have created "make box" to have a check on the time differences after reboot of the system, and there is a correlation about it. Sometimes the difference is as much as 800ms but it is relativly stable within that range.

I might be guessing here but it seems that the uptime() counter is started a little bit after the real system boot. As "man proc(5)" says that the start /proc/x/stat starttime is based on the boot time ticks I would say that a btime base is more correct.

I' ll leave the code for Variant 1 and Variant 2 for a while, so that one can resivit that. But I think the new get_boottime() value is even low enough to remove an older EpsilonTime patch.

**Comment by gdraheim** [comment]
boot time should work now on the "develop" branch. As it may change the behaviour of existing containers, I have put that into a new generation v1.5 - to be released next month. The current v1.4 generation had a last release today.

**Comment by gdraheim** [comment]
The new release is quite stable now on develop.
